# generated by datamodel-codegen:
#   filename:  client_connect.json
#   timestamp: 2021-07-18T15:28:20+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, constr


class Server(BaseModel):
    name: constr(min_length=1) = Field(
        ...,
        description="The configured name for the server, matches ID when unconfigured",
    )
    host: str = Field(
        ..., description="The host this server runs on, typically a IP address"
    )
    id: str = Field(..., description="The unique server ID for this node")
    cluster: Optional[str] = Field(
        None, description="The cluster the server belongs to"
    )
    ver: str = Field(..., description="The version NATS running on the server")
    seq: int = Field(..., description="Internal server sequence ID")
    jetstream: bool = Field(
        ..., description="Indicates if this server has JetStream enabled"
    )
    time: str = Field(..., description="The local time of the server")


class Client(BaseModel):
    start: Optional[str] = Field(
        None, description="Timestamp when the client connected"
    )
    stop: Optional[str] = Field(
        None, description="Timestamp when the client disconnected"
    )
    host: Optional[str] = Field(
        None, description="The remote host the client is connected from"
    )
    id: Optional[str] = Field(
        None, description="The internally assigned client ID for this connection"
    )
    acc: str = Field(..., description="The account this user logged in to")
    user: Optional[str] = Field(None, description="The clients username")
    name: Optional[str] = Field(
        None, description="The name presented by the client during connection"
    )
    lang: Optional[str] = Field(
        None, description="The programming language library in use by the client"
    )
    ver: Optional[str] = Field(
        None, description="The version of the client library in use"
    )
    rtt: Optional[float] = Field(
        None,
        description="The last known latency between the NATS Server and the Client in nanoseconds",
    )
    server: Optional[str] = Field(
        None, description="The server that the client was connected to"
    )
    cluster: Optional[str] = Field(
        None, description="The cluster name the server is connected to"
    )
    jwt: Optional[str] = Field(None, description="The JWT presented in the connection")
    issuer_key: Optional[str] = Field(
        None,
        description="The public signing key or account identity key used to issue the user",
    )
    name_tag: Optional[str] = Field(
        None, description="The name extracted from the user JWT claim"
    )
    tags: Optional[List[str]] = Field(None, description="Tags extracted from the JWT")


class IoNatsServerAdvisoryV1ClientConnect(BaseModel):
    type: str
    id: str = Field(..., description="Unique correlation ID for this event")
    timestamp: str = Field(
        ..., description="The time this event was created in RFC3339 format"
    )
    server: Server = Field(
        ..., description="Details about the server the client connected to"
    )
    client: Client = Field(
        ..., description="Details about the client that connected to the server"
    )
