# generated by datamodel-codegen:
#   filename:  server_out_of_space.json
#   timestamp: 2021-07-18T15:28:14+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class IoNatsJetstreamAdvisoryV1ServerOutOfSpace(BaseModel):
    type: str
    id: str = Field(..., description="Unique correlation ID for this event")
    timestamp: str = Field(
        ..., description="The time this event was created in RFC3339 format"
    )
    stream: Optional[str] = Field(
        None, description="The Stream that triggered the out of space event"
    )
    server: str = Field(..., description="The server name that ran out of space")
    server_id: str = Field(..., description="The server ID that ran out of space")
    cluster: Optional[str] = Field(None, description="The cluster the server is in")
