# generated by datamodel-codegen:
#   filename:  stream_action.json
#   timestamp: 2021-07-18T15:28:09+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class Action(Enum):
    create = "create"
    delete = "delete"
    modify = "modify"


class IoNatsJetstreamAdvisoryV1StreamAction(BaseModel):
    type: str
    id: str = Field(..., description="Unique correlation ID for this event")
    timestamp: str = Field(
        ..., description="The time this event was created in RFC3339 format"
    )
    action: Action = Field(..., description="The action that the event describes")
    stream: str = Field(..., description="The name of the Stream that's acted on")
    template: Optional[str] = Field(
        None, description="The Stream Template that manages the Stream"
    )
