# generated by datamodel-codegen:
#   filename:  terminated.json
#   timestamp: 2021-07-18T15:28:16+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, conint


class IoNatsJetstreamAdvisoryV1Terminated(BaseModel):
    type: str
    id: str = Field(..., description="Unique correlation ID for this event")
    timestamp: str = Field(
        ..., description="The time this event was created in RFC3339 format"
    )
    stream: str = Field(
        ..., description="The name of the stream where the message is stored"
    )
    consumer: str = Field(
        ..., description="The name of the consumer where the message was terminated"
    )
    stream_seq: str = Field(
        ..., description="The sequence of the message in the stream that was terminated"
    )
    consumer_seq: str = Field(
        ...,
        description="The sequence of the message in the consumer that was terminated",
    )
    deliveries: conint(ge=1) = Field(
        ..., description="The number of deliveries that were attempted"
    )
