# generated by datamodel-codegen:
#   filename:  account_info_response.json
#   timestamp: 2021-07-18T15:27:44+00:00

from __future__ import annotations

from typing import Optional, Union

from pydantic import BaseModel, Field, conint


class IoNatsJetstreamApiV1AccountInfoResponse1(BaseModel):
    type: str


class Limits(BaseModel):
    max_memory: conint(ge=-1) = Field(
        ...,
        description="The maximum amount of Memory storage Stream Messages may consume",
    )
    max_storage: conint(ge=-1) = Field(
        ...,
        description="The maximum amount of File storage Stream Messages may consume",
    )
    max_streams: conint(ge=-1) = Field(
        ..., description="The maximum number of Streams an account can create"
    )
    max_consumers: conint(ge=-1) = Field(
        ..., description="The maximum number of Consumer an account can create"
    )


class Api(BaseModel):
    total: conint(ge=0) = Field(
        ..., description="Total number of API requests received for this account"
    )
    errors: conint(ge=0) = Field(
        ..., description="API requests that resulted in an error response"
    )


class IoNatsJetstreamApiV1AccountInfoResponseItem(BaseModel):
    memory: conint(ge=0) = Field(
        ..., description="Memory Storage being used for Stream Message storage"
    )
    storage: conint(ge=0) = Field(
        ..., description="File Storage being used for Stream Message storage"
    )
    streams: conint(ge=0) = Field(..., description="Number of active Streams")
    consumers: conint(ge=0) = Field(..., description="Number of active Consumers")
    limits: Limits
    api: Api


class Error(BaseModel):
    code: conint(ge=300, le=699) = Field(
        ..., description="HTTP like error code in the 300 to 500 range"
    )
    description: Optional[str] = Field(
        None, description="A human friendly description of the error"
    )


class IoNatsJetstreamApiV1AccountInfoResponseItem1(BaseModel):
    error: Error


class IoNatsJetstreamApiV1AccountInfoResponse(BaseModel):
    __root__: Union[
        IoNatsJetstreamApiV1AccountInfoResponseItem,
        IoNatsJetstreamApiV1AccountInfoResponseItem1,
        IoNatsJetstreamApiV1AccountInfoResponse1,
    ] = Field(
        ...,
        description="A response from the JetStream $JS.API.INFO API",
        title="io.nats.jetstream.api.v1.account_info_response",
    )
