# generated by datamodel-codegen:
#   filename:  consumer_names_response.json
#   timestamp: 2021-07-18T15:27:56+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, conint


class IoNatsJetstreamApiV1ConsumerNamesResponse(BaseModel):
    total: conint(ge=0)
    offset: conint(ge=0)
    limit: conint(ge=0)
    type: str
    consumers: List[str] = []
