# generated by datamodel-codegen:
#   filename:  consumer_list_request.json
#   timestamp: 2021-07-18T15:27:53+00:00

from __future__ import annotations

from pydantic import BaseModel, conint


class IoNatsJetstreamApiV1ConsumerListRequest(BaseModel):
    offset: conint(ge=0)
