# generated by datamodel-codegen:
#   filename:  consumer_delete_response.json
#   timestamp: 2021-07-18T15:27:46+00:00

from __future__ import annotations

from typing import Optional, Union

from pydantic import BaseModel, Field, conint


class IoNatsJetstreamApiV1ConsumerDeleteResponse1(BaseModel):
    type: str


class Error(BaseModel):
    code: conint(ge=300, le=699) = Field(
        ..., description="HTTP like error code in the 300 to 500 range"
    )
    description: Optional[str] = Field(
        None, description="A human friendly description of the error"
    )


class IoNatsJetstreamApiV1ConsumerDeleteResponseItem(BaseModel):
    error: Error


class IoNatsJetstreamApiV1ConsumerDeleteResponseItem1(BaseModel):
    success: bool


class IoNatsJetstreamApiV1ConsumerDeleteResponse(BaseModel):
    __root__: Union[
        IoNatsJetstreamApiV1ConsumerDeleteResponse1,
        IoNatsJetstreamApiV1ConsumerDeleteResponseItem,
        IoNatsJetstreamApiV1ConsumerDeleteResponseItem1,
    ] = Field(
        ...,
        description="A response from the JetStream $JS.API.CONSUMER.DELETE API",
        title="io.nats.jetstream.api.v1.consumer_delete_response",
    )
