# generated by datamodel-codegen:
#   filename:  consumer_names_request.json
#   timestamp: 2021-07-18T15:28:01+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field, conint


class IoNatsJetstreamApiV1ConsumerNamesRequest(BaseModel):
    offset: conint(ge=0)
    subject: Optional[str] = Field(
        None,
        description="Filter the names to those consuming messages matching this subject or wildcard",
    )
