# generated by datamodel-codegen:
#   filename:  consumer_getnext_request.json
#   timestamp: 2021-07-18T15:27:42+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field, conint


class IoNatsJetstreamApiV1ConsumerGetnextRequest(BaseModel):
    expires: Optional[int] = Field(
        None,
        description="A duration from now when the pull should expire, stated in nanoseconds, 0 for no expiry",
    )
    batch: Optional[conint(ge=0, le=256)] = Field(
        None, description="How many messages the server should deliver to the requestor"
    )
    no_wait: Optional[bool] = Field(
        None,
        description="When true a response with a 404 status header will be returned when no messages are available",
    )
