# generated by datamodel-codegen:
#   filename:  meta_leader_stepdown_request.json
#   timestamp: 2021-07-18T15:28:02+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, constr


class Placement(BaseModel):
    cluster: constr(min_length=1) = Field(
        ..., description="The desired cluster name to place the stream"
    )
    tags: Optional[List[str]] = Field(
        None, description="Tags required on servers hosting this stream"
    )


class IoNatsJetstreamApiV1MetaLeaderStepdownRequest(BaseModel):
    placement: Optional[Placement] = Field(
        None, description="Placement requirements for a stream"
    )
