# generated by datamodel-codegen:
#   filename:  meta_server_remove_request.json
#   timestamp: 2021-07-18T15:28:04+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class IoNatsJetstreamApiV1MetaServerRemoveRequest(BaseModel):
    peer: str = Field(
        ..., description="The Name of the server to remove from the meta group"
    )
