# generated by datamodel-codegen:
#   filename:  stream_list_request.json
#   timestamp: 2021-07-18T15:27:59+00:00

from __future__ import annotations

from pydantic import BaseModel, conint


class IoNatsJetstreamApiV1StreamListRequest(BaseModel):
    offset: conint(ge=0)
