# generated by datamodel-codegen:
#   filename:  stream_list_response.json
#   timestamp: 2021-07-18T15:28:08+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, conint

from .stream_info_response import IoNatsJetstreamApiV1StreamInfoResponseItem


class IoNatsJetstreamApiV1StreamListResponse(BaseModel):
    total: conint(ge=0)
    offset: conint(ge=0)
    limit: conint(ge=0)
    type: str
    streams: List[IoNatsJetstreamApiV1StreamInfoResponseItem] = []
