# generated by datamodel-codegen:
#   filename:  stream_snapshot_request.json
#   timestamp: 2021-07-18T15:27:38+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field, conint, constr


class IoNatsJetstreamApiV1StreamSnapshotRequest(BaseModel):
    deliver_subject: constr(min_length=1) = Field(
        ..., description="The NATS subject where the snapshot will be delivered"
    )
    no_consumers: Optional[bool] = Field(
        None,
        description="When true consumer states and configurations will not be present in the snapshot",
    )
    chunk_size: Optional[conint(ge=1024)] = Field(
        None, description="The size of data chunks to send to deliver_subject"
    )
    jsck: Optional[bool] = Field(
        False, description="Check all message's checksums prior to snapshot"
    )
