# generated by datamodel-codegen:
#   filename:  stream_info_request.json
#   timestamp: 2021-07-18T15:27:49+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class IoNatsJetstreamApiV1StreamInfoRequest(BaseModel):
    deleted_details: Optional[bool] = Field(
        None,
        description="When true will result in a full list of deleted message IDs being returned in the info response",
    )
