# generated by datamodel-codegen:
#   filename:  stream_msg_delete_request.json
#   timestamp: 2021-07-18T15:28:06+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class IoNatsJetstreamApiV1StreamMsgDeleteRequest(BaseModel):
    seq: int = Field(..., description="Stream sequence number of the message to delete")
    no_erase: Optional[bool] = Field(
        None,
        description="Default will securely remove a message and rewrite the data with random data, set this to true to only remove the message",
    )
