# generated by datamodel-codegen:
#   filename:  stream_msg_delete_response.json
#   timestamp: 2021-07-18T15:28:00+00:00

from __future__ import annotations

from typing import Optional, Union

from pydantic import BaseModel, Field, conint


class IoNatsJetstreamApiV1StreamMsgDeleteResponse1(BaseModel):
    type: str


class Error(BaseModel):
    code: conint(ge=300, le=699) = Field(
        ..., description="HTTP like error code in the 300 to 500 range"
    )
    description: Optional[str] = Field(
        None, description="A human friendly description of the error"
    )


class IoNatsJetstreamApiV1StreamMsgDeleteResponseItem(BaseModel):
    error: Error


class IoNatsJetstreamApiV1StreamMsgDeleteResponseItem1(BaseModel):
    success: bool


class IoNatsJetstreamApiV1StreamMsgDeleteResponse(BaseModel):
    __root__: Union[
        IoNatsJetstreamApiV1StreamMsgDeleteResponse1,
        IoNatsJetstreamApiV1StreamMsgDeleteResponseItem,
        IoNatsJetstreamApiV1StreamMsgDeleteResponseItem1,
    ] = Field(
        ...,
        description="A response from the JetStream $JS.API.STREAM.MSG.DELETE API",
        title="io.nats.jetstream.api.v1.stream_msg_delete_response",
    )
