# generated by datamodel-codegen:
#   filename:  stream_restore_response.json
#   timestamp: 2021-07-18T15:27:54+00:00

from __future__ import annotations

from typing import Optional, Union

from pydantic import BaseModel, Field, conint, constr


class IoNatsJetstreamApiV1StreamRestoreResponse1(BaseModel):
    type: Optional[str] = None


class Error(BaseModel):
    code: conint(ge=300, le=699) = Field(
        ..., description="HTTP like error code in the 300 to 500 range"
    )
    description: Optional[str] = Field(
        None, description="A human friendly description of the error"
    )


class IoNatsJetstreamApiV1StreamRestoreResponseItem(BaseModel):
    error: Error


class IoNatsJetstreamApiV1StreamRestoreResponseItem1(BaseModel):
    deliver_subject: constr(min_length=1) = Field(
        ..., description="The Subject to send restore chunks to"
    )


class IoNatsJetstreamApiV1StreamRestoreResponse(BaseModel):
    __root__: Union[
        IoNatsJetstreamApiV1StreamRestoreResponse1,
        IoNatsJetstreamApiV1StreamRestoreResponseItem,
        IoNatsJetstreamApiV1StreamRestoreResponseItem1,
    ] = Field(
        ...,
        description="A response from the JetStream $JS.API.STREAM.RESTORE API",
        title="io.nats.jetstream.api.v1.stream_restore_response",
    )
