# generated by datamodel-codegen:
#   filename:  stream_msg_get_request.json
#   timestamp: 2021-07-18T15:28:03+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class IoNatsJetstreamApiV1StreamMsgGetRequest(BaseModel):
    seq: int = Field(
        ..., description="Stream sequence number of the message to retrieve"
    )
