# generated by datamodel-codegen:
#   filename:  stream_template_names_request.json
#   timestamp: 2021-07-18T15:27:47+00:00

from __future__ import annotations

from pydantic import BaseModel, conint


class IoNatsJetstreamApiV1StreamTemplateNamesRequest(BaseModel):
    offset: conint(ge=0)
