# generated by datamodel-codegen:
#   filename:  stream_template_names_response.json
#   timestamp: 2021-07-18T15:28:07+00:00

from __future__ import annotations

from pydantic import BaseModel, conint


class IoNatsJetstreamApiV1StreamTemplateNamesResponse(BaseModel):
    total: conint(ge=0)
    offset: conint(ge=0)
    limit: conint(ge=0)
    type: str
