# generated by datamodel-codegen:
#   filename:  consumer_ack.json
#   timestamp: 2021-07-18T15:27:36+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, conint


class IoNatsJetstreamMetricV1ConsumerAck(BaseModel):
    type: str
    id: str = Field(..., description="Unique correlation ID for this event")
    timestamp: str = Field(
        ..., description="The time this event was created in RFC3339 format"
    )
    stream: str = Field(
        ..., description="The name of the stream where the message is stored"
    )
    consumer: str = Field(
        ..., description="The name of the consumer where the message is held"
    )
    stream_seq: conint(ge=1) = Field(
        ...,
        description="The sequence of the message in the stream that were acknowledged",
    )
    consumer_seq: conint(ge=1) = Field(
        ...,
        description="The sequence of the message in the consumer that were acknowledged",
    )
    ack_time: conint(ge=1) = Field(
        ...,
        description="The time it took on the final delivery for the message to be acknowledged in nanoseconds",
    )
    deliveries: conint(ge=1) = Field(
        ...,
        description="The number of deliveries that were attempted before being acknowledged",
    )
